name: "Static Memory Management Test"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  static-memory:
    name: Build Arduino and non-Arduino with enabled static memory management
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies for unit test
      run: |
        sudo apt-get update
        sudo apt-get install -y libboost-all-dev libfmt-dev lcov

    - name: Run unit test for static memory management
      run: |
        cd extras/test/unit
        ./test.sh -DRADIOLIB_STATIC_ONLY

    - name: Install arduino-cli
      run:
        |
        mkdir -p ~/.local/bin
        echo "~/.local/bin" >> $GITHUB_PATH
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=~/.local/bin sh

    - name: Install platform
      run:
        |
        arduino-cli core update-index
        arduino-cli core install arduino:avr

    - name: Build Arduino example
      run:
        arduino-cli compile --libraries /home/runner/work/RadioLib --fqbn arduino:avr:mega $PWD/examples/SX123x/SX123x_Transmit_Blocking/SX123x_Transmit_Blocking.ino --warnings=all --build-property compiler.cpp.extra_flags="-DRADIOLIB_STATIC_ONLY"

    
